cancion_favorita = input("¿Cuál es tu canción favorita?")
artista = input("¿De qué artista es?")
album = input("¿Pertenece a algún álbum? Si la respuesta es si, ¿a cuál?")
año_lanzamiento = int(input("¿Cuál fue el año de lanzamiento?"))
duracion = float(input("¿Cuánto dura en segundos?"))
videoclip = input("¿Tiene videoclip?")

print("Mi canción favorita es", cancion_favorita)
print("Pertenece al artista/banda", artista)
print("Pertenece al álbum", album)
print("Salió en el año", año_lanzamiento)
print("Tiene una duración de", duracion)
print("¿Tiene videoclip?", videoclip)

peor_cancion = input("¿Cuál es la canción que menos te gusta?")
artista = input("¿De qué artista es?")
album = input("¿Pertenece a algún álbum? Si la respuesta es si, ¿a cuál?")
año_lanzamiento = int(input("¿Cuál fue el año de lanzamiento?"))
duracion = float(input("¿Cuánto dura en segundos?"))
videoclip = input("¿Tiene videoclip?")

print("La canción que menos me gusta es", peor_cancion)
print("Pertenece al artista/banda", artista)
print("Pertenece al álbum", album)
print("Salió en el año", año_lanzamiento)
print("Tiene una duración de", duracion)
print("¿Tiene videoclip?", videoclip)